//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        public int idPost { get; set; }
        public string TextPost { get; set; }
        public byte[] ImagePost { get; set; }
        public string MusicPath { get; set; }
        public string VideoPath { get; set; }
        public Nullable<int> idUser { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
